apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels: 
    app: mydemoapp
  namespace: dev
spec: 
  containers:
    - name: mypod
      image: nginx:1.29
      ports:
        - containerPort: 80
